default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tic-tac-toe-service_development
  username: cyrus

test:
  <<: *default
  database: tic-tac-toe-service_test
  username: cyrus

production:
  <<: *default
  database: tic-tac-toe-service_production
  username: tic-tac-toe-service
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
